export const triviaTopics = [
  // 1. MOVIES
  'Classic Cinema – Pre-2000s films, iconic directors, Oscar winners.',
  'Blockbuster Movies – Billion-dollar films, franchises, box office records.',
  'Cult Classics – Quirky films with passionate fanbases.',
  'Animated Movies – Pixar, Disney, DreamWorks, and animated trivia.',
  'Movie Quotes – Guess the film from the iconic line.',
  '80s Movies – Action, comedy, teen classics from the decade.',
  '90s Movies – Rom-coms, blockbusters, indie hits from the 90s.',
  '2000s Movies – Early 21st century hits, new franchises, modern classics.',
  'Horror Movies – Slashers, supernatural tales, iconic horror villains.',
  'Musicals on Film – Movie musicals from classic to modern times.',
  'Superhero Films – Marvel, DC, and comic-book adaptations.',
  'Movie Soundtracks – Famous songs tied to films.',
  'Oscar Best Picture Winners – Films that took home the top prize.',
  'Oscar Snubs & Surprises – Movies that lost or shocked the Academy.',
  'Steven Spielberg Films – From Jaws to Jurassic Park and beyond.',
  'Christopher Nolan Films – Mind-bending plots, time twists, epic scores.',
  'Quentin Tarantino Films – Stylish violence, snappy dialogue, cult appeal.',
  'Martin Scorsese Films – Mafia tales, character studies, cinematic mastery.',
  'Classic Action Movies – Explosions, one-liners, 80s and 90s action heroes.',
  'Romantic Comedies – Love stories, meet-cutes, and comedic mishaps.',
  'Fantasy Films – Epic quests, magical creatures, and legendary worlds.',
  'Historical Epics – Braveheart, Gladiator, Ben-Hur, sweeping historical tales.',
  'War Movies – Depictions of conflict from WWII to modern warfare.',
  'Sci-Fi Cinema – Space adventures, robots, dystopian futures.',
  'Movie Franchises – Star Wars, The Matrix, James Bond, and big series.',
  'Sports Movies – Underdogs, true stories, and iconic sports moments.',
  'Animated Classics – Early Disney, Looney Tunes, classic animation trivia.',
  'Documentaries – Non-fiction films that captivated audiences.',
  'Film Noir – Shadows, detectives, and femme fatales.',
  'Indie Films – Festival darlings, low-budget gems, and cult indies.',
  'Foreign Films – International cinema, subtitles, and award winners.',
  'Movie Villains – Iconic baddies, memorable performances, evil plans.',
  'Cinematic Visual Effects – Groundbreaking CGI, practical effects, and movie magic.',

  // 2. TELEVISION
  '90s TV Sitcoms – Friends, Seinfeld, Frasier, and classic laughs.',
  '90s TV Dramas – Buffy, The X-Files, ER, and intense storylines.',
  '90s Kids Shows – Nickelodeon classics, cartoons, and after-school hits.',
  '90s Game Shows – Legends of the Hidden Temple, Double Dare, and more.',
  '2000s TV Sitcoms – The Office, Scrubs, How I Met Your Mother.',
  '2000s TV Dramas – Lost, 24, Grey’s Anatomy, thrilling plots.',
  '2000s Reality TV – Survivor, American Idol, The Amazing Race.',
  '2000s Kids & Teen Shows – Disney Channel and Nickelodeon hits.',
  'The Office Trivia – U.S. series quotes, episodes, characters.',
  'Friends Trivia – Characters, episodes, iconic quotes.',
  'Seinfeld Trivia – Episodes, catchphrases, quirky side characters.',
  'Reality TV – Competitive shows, dating chaos, culinary drama.',
  'Classic Sitcoms – I Love Lucy, Cheers, The Golden Girls.',
  'Classic TV Dramas – Dallas, Dynasty, Hill Street Blues.',
  'Streaming Hits – Netflix, Hulu, Prime originals and trends.',
  'Netflix Originals – Stranger Things, The Witcher, Bridgerton.',
  'HBO Originals – Sopranos, Game of Thrones, Succession.',
  'British TV – Doctor Who, The Crown, Fleabag.',
  'British Sitcoms – The Office UK, Absolutely Fabulous, Blackadder.',
  'British Mysteries – Sherlock, Broadchurch, Midsomer Murders.',
  'TV Theme Songs – Name the show from the theme tune.',
  'Animated TV Shows – Simpsons, Family Guy, Rick and Morty.',
  'Adult Animated Series – South Park, BoJack Horseman, Archer.',
  'Animated Kids TV – Scooby-Doo, Rugrats, Adventure Time.',
  'TV Villains – Iconic bad guys and girls from TV history.',
  'Cult TV Shows – Twin Peaks, Firefly, Freaks and Geeks.',
  'Soap Operas – Days of Our Lives, General Hospital, dramatic twists.',
  'TV Sci-Fi & Fantasy – Star Trek, Battlestar Galactica, fantasy epics.',
  'TV Reboots & Revivals – From Fuller House to Twin Peaks.',
  'TV Miniseries – Iconic limited-run shows, from Chernobyl to Band of Brothers.',

  // 3. GEOGRAPHY & TRAVEL
  'World Geography – Capitals, landmarks, borders, natural wonders.',
  'U.S. Geography – States, capitals, national parks, famous places.',
  'Cities of the World – Famous skylines, neighborhoods, city nicknames.',
  'Mountains, Lakes & Rivers – Natural landmarks across the globe.',
  'Travel & Tourism – Famous sights, must-visit destinations, UNESCO sites.',
  'European Geography – Countries, landmarks, cultures.',
  'Asian Geography – Nations, capitals, famous sites.',
  'Oceans & Seas – Marine geography, famous coastal features.',
  'Flags of the World – Identify countries by their flags.',
  'Transportation & Travel – Airlines, trains, famous routes.',
  'U.S. State Capitals – Match the capital to its state.',
  'U.S. National Parks – Famous parks, locations, and natural wonders.',
  'U.S. State Nicknames – The Empire State, The Sunshine State, etc.',
  'U.S. Borders & Regions – Great Plains, Midwest, New England, etc.',
  'Canadian Geography – Provinces, cities, natural landmarks.',
  'South American Geography – Countries, capitals, Amazon River facts.',
  'African Geography – Countries, deserts, famous wildlife regions.',
  'Australian & Oceania Geography – Outback, islands, unique animals.',
  'Middle East Geography – Countries, landmarks, cultural regions.',
  'Polar Regions – Arctic and Antarctic geography, ice sheets, wildlife.',
  'Deserts of the World – From the Sahara to the Gobi.',
  'Islands & Archipelagos – From Hawaii to the Maldives.',
  'Peninsulas of the World – Iberian, Korean, Florida and beyond.',
  'World Rivers – Nile, Amazon, Yangtze, and famous river facts.',
  'World Mountains – Everest, Kilimanjaro, the Rockies.',
  'World Wonders – Seven wonders ancient and modern.',
  'Time Zones & Date Line – Global time trivia.',
  'Smallest Countries – Micronations and tiny countries.',
  'Border Oddities – Exclaves, enclaves, disputed territories.',
  'Geography Superlatives – Largest, smallest, highest, deepest places.',

  // 4. MUSIC
  'Pop Music Through the Decades – From Elvis to Beyoncé.',
  'Classic Rock – Bands, albums, iconic songs.',
  'Hip-Hop & Rap – Artists, albums, lyrics, milestones.',
  'One-Hit Wonders – Artists who had a single big hit.',
  'Music Lyrics – Name the song from a snippet of lyrics.',
  'Country Music – Legends, lyrics, and modern stars.',
  'Indie & Alternative – Bands and hits outside the mainstream.',
  'Music Videos – Identify songs by iconic music videos.',
  'Grammy Awards – Winners, records, controversies.',
  'Music Festivals – Coachella, Glastonbury, Lollapalooza.',

  // 5. SCIENCE & NATURE
  'Science & Nature – Chemistry, biology, animals, the natural world.',
  'Space & Astronomy – Planets, NASA missions, stars, and cosmic trivia.',
  'Human Body – Anatomy, organs, medical oddities.',
  'Inventions & Discoveries – Inventors, breakthroughs, tech history.',
  'Weather & Natural Disasters – Tornadoes, hurricanes, extreme weather facts.',
  'Dinosaurs & Fossils – Prehistoric creatures and paleontology.',
  'Marine Life – Ocean animals, coral reefs, deep-sea creatures.',
  'Birds & Birdwatching – Species, calls, migration facts.',
  'Endangered Species – Animals at risk, conservation facts.',
  'Physics & Engineering – Laws of nature and famous experiments.',

  // 6. LITERATURE & ARTS
  'Literature & Books – Authors, opening lines, banned books.',
  'Children’s Books – Dr. Seuss, Harry Potter, Roald Dahl, classics.',
  'Mystery & Crime Novels – Famous detectives, authors, and twists.',
  'Shakespeare – Plays, quotes, historical context.',
  'Famous Biographies – Lives of notable figures, from artists to athletes.',
  'Poetry & Poets – Famous verses, poets across history.',
  'Fairy Tales & Folklore – Stories from around the world.',
  'Graphic Novels & Comics – Marvel, DC, manga, indie comics.',
  'Art & Artists – Famous paintings, artists, art movements.',
  'Philosophy & Thinkers – Famous philosophers and big ideas.',

  // 7. HISTORY & CULTURE
  'History & Politics – Wars, leaders, revolutions.',
  'U.S. Presidents – Fun facts, pets, speeches, and quirks.',
  'British Royal History – Monarchs, scandals, royal weddings.',
  'Historical Oddities – Weird events, bizarre laws, strange deaths.',
  'Ancient Civilizations – Greeks, Romans, Egyptians, and others.',
  'World Wars – Key battles, leaders, and events from WWI & WWII.',
  'Women in History – Trailblazing women across fields.',
  'Famous Speeches – Identify the speaker and moment.',
  'Cold War History – Espionage, nuclear tensions, Berlin Wall.',
  'Explorers & Expeditions – Voyages of discovery around the world.',

  // 8. FOOD & DRINK
  'Food & Drink – Cuisine, cocktails, famous chefs.',
  'International Cuisines – Regional dishes, spices, and traditions.',
  'Cocktail Culture – Classic recipes, spirits, and mixology trivia.',
  'Sweet Treats – Candy, desserts, pastries from around the world.',
  'Fast Food & Chains – Menu items, mascots, brand trivia.',
  'Coffee & Tea Culture – Beans, brews, and ceremonies.',
  'Cheese & Dairy – Cheeses of the world, fun dairy facts.',
  'Beer & Brewing – Types of beer, breweries, brewing history.',
  'Wine & Vineyards – Regions, grapes, and wine trivia.',
  'Vegetarian & Vegan Cuisine – Plant-based dishes, chefs, trends.',

  // 9. SPORTS & GAMES
  'Sports & Games – Olympics, chess, soccer, Super Bowl MVPs.',
  'NFL Trivia – Teams, players, records, Super Bowls.',
  'NBA Trivia – Teams, MVPs, legendary games.',
  'Olympic History – Unforgettable moments, medal counts, host cities.',
  'Board Games & Puzzles – Trivial Pursuit, Monopoly, chess trivia.',
  'Soccer / Football – Clubs, players, World Cup trivia.',
  'Baseball Trivia – MLB teams, history, stats.',
  'Tennis – Grand Slam winners, famous matches.',
  'Extreme Sports – X Games, skateboarding, snowboarding.',
  'Esports & Video Games – Games, streamers, tournaments.',
  'NHL & Ice Hockey – Stanley Cup winners, legendary players, rules.',
  'Golf Trivia – The Masters, famous golfers, iconic shots.',
  'Boxing & MMA – Champions, famous bouts, fighting organizations.',
  'Auto Racing – Formula 1, NASCAR, legendary races and drivers.',
  'Track & Field – World records, Olympic heroes, iconic races.',
  'Gymnastics – Olympic champions, scoring, memorable routines.',
  'Cricket – Test matches, World Cups, legendary players.',
  'Rugby – Union, League, World Cups, legendary teams.',
  'Wrestling Entertainment – WWE superstars, iconic matches, storylines.',
  'Winter Sports – Skiing, snowboarding, biathlon, and icy competitions.',

  // 10. FUN & RANDOM
  'Weird But True – Guinness records, strange inventions, odd laws.',
  'Famous Quotes – Identify who said it: from politicians to celebrities.',
  'Famous Firsts – First in history across various fields.',
  'Mythology & Legends – Greek, Norse, Egyptian myths, urban legends.',
  'Pop Culture Moments – Viral trends, memes, internet history.',
  'Fashion & Designers – Iconic styles, brands, runway history.',
  'Toys & Childhood Nostalgia – From Barbie to Pokémon cards.',
  'Languages & Words – Etymology, rare words, language trivia.',
  'Animals in Pop Culture – Famous fictional pets, mascots, and creatures.',
  'Holidays & Traditions – Christmas, Diwali, Halloween customs worldwide.',

  // 11. TECHNOLOGY & DIGITAL LIFE
  'Computers & Internet History – Milestones from ENIAC to the modern web.',
  'Tech Companies & Founders – Apple, Google, Microsoft, and the minds behind them.',
  'Apps & Social Media – Instagram, TikTok, Twitter trivia.',
  'Gadgets Through Time – From Walkmans to smartphones.',
  'Cybersecurity & Hacking – Famous hacks, encryption, and online safety.',
  'Digital Innovations – AI, VR, blockchain, and emerging tech.',
  'Gaming Hardware – Consoles, graphics cards, and retro systems.',
  'Smartphones & Devices – Mobile tech, apps, and market trends.',
  'Tech Buzzwords – Cloud, big data, IoT and what they mean.',
  'Digital Pop Culture – Memes, viral videos, and internet icons.',

  // 12. BUSINESS & ECONOMICS
  'Famous Entrepreneurs – Visionaries who built empires.',
  'Stock Market Basics – Indices, ticker symbols, and Wall Street trivia.',
  'Brands & Logos – Recognize the brand by its logo.',
  'Corporate Scandals – Shocking frauds and business failures.',
  'Advertising & Marketing – Famous slogans, campaigns, and jingles.',
  'Business History – Industrial revolutions, historical companies.',
  'Consumer Products – Everyday items and their origins.',
  'Startups & Unicorns – Companies that boomed fast.',
  'Global Trade – Imports, exports, and trade partners.',
  'Billionaires Club – The world’s wealthiest people and facts about them.',

  // 13. LIFESTYLE & WELLNESS
  'Fitness & Exercise – Workouts, sports science, and trends.',
  'Meditation & Mindfulness – Practices, benefits, and origins.',
  'Healthy Eating – Superfoods, nutrition facts, diet trends.',
  'Fashion Trends – Styles through the decades.',
  'Home Décor & DIY – Interior design, crafting, and home projects.',
  'Pets & Animal Care – Breeds, fun facts, and famous pets.',
  'Gardening & Plants – Flowers, veggies, and gardening trivia.',
  'Travel Hacks – Tips, tricks, and travel trivia.',
  'Personal Finance – Saving, budgeting, and financial literacy.',
  'Self-Care & Happiness – Tips for well-being and feel-good trivia.',
]
