export const triviaTopics = [
  'Classic Cinema – Pre-2000s films, iconic directors, Oscar winners.',
  'Blockbuster Movies – Billion-dollar films, franchises, box office records.',
  'Cult Classics – Quirky films with passionate fanbases.',
  'Animated Movies – Pixar, Disney, DreamWorks, and animated trivia.',
  'Movie Quotes – Guess the film from the iconic line.',
  '90s TV Shows – Friends, Seinfeld, Buffy, and more.',
  'TV Shows of the 2000s – Lost, Breaking Bad, The Office.',
  'The Office Trivia – Characters, quotes, plot lines from the U.S. series.',
  'Friends Trivia – Characters, episodes, famous quotes.',
  'Reality TV – Survivor, The Bachelor, Top Chef, and dramatic moments.',
  'World Geography – Capitals, landmarks, borders, natural wonders.',
  'U.S. Geography – States, capitals, national parks, famous places.',
  'Cities of the World – Famous skylines, neighborhoods, city nicknames.',
  'Mountains, Lakes & Rivers – Natural landmarks across the globe.',
  'Travel & Tourism – Famous sights, must-visit destinations, UNESCO sites.',
  'Pop Music Through the Decades – From Elvis to Beyoncé.',
  'Classic Rock – Bands, albums, iconic songs.',
  'Hip-Hop & Rap – Artists, albums, lyrics, milestones.',
  'One-Hit Wonders – Artists who had a single big hit.',
  'Music Lyrics – Name the song from a snippet of lyrics.',
  'Science & Nature – Chemistry, biology, animals, the natural world.',
  'Space & Astronomy – Planets, NASA missions, stars, and cosmic trivia.',
  'Human Body – Anatomy, organs, medical oddities.',
  'Inventions & Discoveries – Inventors, breakthroughs, tech history.',
  'Weather & Natural Disasters – Tornadoes, hurricanes, extreme weather facts.',
  'Literature & Books – Authors, opening lines, banned books.',
  'Children’s Books – Dr. Seuss, Harry Potter, Roald Dahl, classics.',
  'Mystery & Crime Novels – Famous detectives, authors, and twists.',
  'Shakespeare – Plays, quotes, historical context.',
  'Famous Biographies – Lives of notable figures, from artists to athletes.',
  'History & Politics – Wars, leaders, revolutions.',
  'U.S. Presidents – Fun facts, pets, speeches, and quirks.',
  'British Royal History – Monarchs, scandals, royal weddings.',
  'Historical Oddities – Weird events, bizarre laws, strange deaths.',
  'Ancient Civilizations – Greeks, Romans, Egyptians, and others.',
  'Food & Drink – Cuisine, cocktails, famous chefs.',
  'International Cuisines – Regional dishes, spices, and traditions.',
  'Cocktail Culture – Classic recipes, spirits, and mixology trivia.',
  'Sweet Treats – Candy, desserts, pastries from around the world.',
  'Fast Food & Chains – Menu items, mascots, brand trivia.',
  'Sports & Games – Olympics, chess, soccer, Super Bowl MVPs.',
  'NFL Trivia – Teams, players, records, Super Bowls.',
  'NBA Trivia – Teams, MVPs, legendary games.',
  'Olympic History – Unforgettable moments, medal counts, host cities.',
  'Board Games & Puzzles – Trivial Pursuit, Monopoly, chess trivia.',
  'Weird But True – Guinness records, strange inventions, odd laws.',
  'Famous Quotes – Identify who said it: from politicians to celebrities.',
  'Famous Firsts – First in history across various fields.',
  'Mythology & Legends – Greek, Norse, Egyptian myths, urban legends.',
  'Pop Culture Moments – Viral trends, memes, internet history.',
]
