export const triviaTopics = [
  // MOVIES
  'Classic Cinema – Pre-2000s films, iconic directors, Oscar winners.',
  'Blockbuster Movies – Billion-dollar films, franchises, box office records.',
  'Cult Classics – Quirky films with passionate fanbases.',
  'Animated Movies – Pixar, Disney, DreamWorks, and animated trivia.',
  'Movie Quotes – Guess the film from the iconic line.',
  '80s Movies – Action, comedy, teen classics from the decade.',
  '90s Movies – Rom-coms, blockbusters, indie hits from the 90s.',
  'Horror Movies – Slashers, supernatural tales, iconic horror villains.',
  'Musicals on Film – Movie musicals from classic to modern times.',
  'Superhero Films – Marvel, DC, and comic-book adaptations.',
  'Movie Soundtracks – Famous songs tied to films.',

  // TELEVISION
  '90s TV Shows – Friends, Seinfeld, Buffy, and more.',
  'TV Shows of the 2000s – Lost, Breaking Bad, The Office.',
  'The Office Trivia – Characters, quotes, plot lines from the U.S. series.',
  'Friends Trivia – Characters, episodes, famous quotes.',
  'Reality TV – Survivor, The Bachelor, Top Chef, and dramatic moments.',
  'Classic Sitcoms – I Love Lucy, Cheers, The Golden Girls.',
  'Streaming Hits – Netflix, Hulu, Prime originals and trends.',
  'British TV – Series like Doctor Who, The Crown, Black Mirror.',
  'TV Theme Songs – Name the show from the theme tune.',
  'Animated TV Shows – Simpsons, Family Guy, Rick and Morty.',

  // GEOGRAPHY & TRAVEL
  'World Geography – Capitals, landmarks, borders, natural wonders.',
  'U.S. Geography – States, capitals, national parks, famous places.',
  'Cities of the World – Famous skylines, neighborhoods, city nicknames.',
  'Mountains, Lakes & Rivers – Natural landmarks across the globe.',
  'Travel & Tourism – Famous sights, must-visit destinations, UNESCO sites.',
  'European Geography – Countries, landmarks, cultures.',
  'Asian Geography – Nations, capitals, famous sites.',
  'Oceans & Seas – Marine geography, famous coastal features.',
  'Flags of the World – Identify countries by their flags.',
  'Transportation & Travel – Airlines, trains, famous routes.',

  // MUSIC
  'Pop Music Through the Decades – From Elvis to Beyoncé.',
  'Classic Rock – Bands, albums, iconic songs.',
  'Hip-Hop & Rap – Artists, albums, lyrics, milestones.',
  'One-Hit Wonders – Artists who had a single big hit.',
  'Music Lyrics – Name the song from a snippet of lyrics.',
  'Country Music – Legends, lyrics, and modern stars.',
  'Indie & Alternative – Bands and hits outside the mainstream.',
  'Music Videos – Identify songs by iconic music videos.',
  'Grammy Awards – Winners, records, controversies.',
  'Music Festivals – Coachella, Glastonbury, Lollapalooza.',

  // SCIENCE & NATURE
  'Science & Nature – Chemistry, biology, animals, the natural world.',
  'Space & Astronomy – Planets, NASA missions, stars, and cosmic trivia.',
  'Human Body – Anatomy, organs, medical oddities.',
  'Inventions & Discoveries – Inventors, breakthroughs, tech history.',
  'Weather & Natural Disasters – Tornadoes, hurricanes, extreme weather facts.',
  'Dinosaurs & Fossils – Prehistoric creatures and paleontology.',
  'Marine Life – Ocean animals, coral reefs, deep-sea creatures.',
  'Birds & Birdwatching – Species, calls, migration facts.',
  'Endangered Species – Animals at risk, conservation facts.',
  'Physics & Engineering – Laws of nature and famous experiments.',

  // LITERATURE & ARTS
  'Literature & Books – Authors, opening lines, banned books.',
  'Children’s Books – Dr. Seuss, Harry Potter, Roald Dahl, classics.',
  'Mystery & Crime Novels – Famous detectives, authors, and twists.',
  'Shakespeare – Plays, quotes, historical context.',
  'Famous Biographies – Lives of notable figures, from artists to athletes.',
  'Poetry & Poets – Famous verses, poets across history.',
  'Fairy Tales & Folklore – Stories from around the world.',
  'Graphic Novels & Comics – Marvel, DC, manga, indie comics.',
  'Art & Artists – Famous paintings, artists, art movements.',
  'Philosophy & Thinkers – Famous philosophers and big ideas.',

  // HISTORY & CULTURE
  'History & Politics – Wars, leaders, revolutions.',
  'U.S. Presidents – Fun facts, pets, speeches, and quirks.',
  'British Royal History – Monarchs, scandals, royal weddings.',
  'Historical Oddities – Weird events, bizarre laws, strange deaths.',
  'Ancient Civilizations – Greeks, Romans, Egyptians, and others.',
  'World Wars – Key battles, leaders, and events from WWI & WWII.',
  'Women in History – Trailblazing women across fields.',
  'Famous Speeches – Identify the speaker and moment.',
  'Cold War History – Espionage, nuclear tensions, Berlin Wall.',
  'Explorers & Expeditions – Voyages of discovery around the world.',

  // FOOD & DRINK
  'Food & Drink – Cuisine, cocktails, famous chefs.',
  'International Cuisines – Regional dishes, spices, and traditions.',
  'Cocktail Culture – Classic recipes, spirits, and mixology trivia.',
  'Sweet Treats – Candy, desserts, pastries from around the world.',
  'Fast Food & Chains – Menu items, mascots, brand trivia.',
  'Coffee & Tea Culture – Beans, brews, and ceremonies.',
  'Cheese & Dairy – Cheeses of the world, fun dairy facts.',
  'Beer & Brewing – Types of beer, breweries, brewing history.',
  'Wine & Vineyards – Regions, grapes, and wine trivia.',
  'Vegetarian & Vegan Cuisine – Plant-based dishes, chefs, trends.',

  // SPORTS & GAMES
  'Sports & Games – Olympics, chess, soccer, Super Bowl MVPs.',
  'NFL Trivia – Teams, players, records, Super Bowls.',
  'NBA Trivia – Teams, MVPs, legendary games.',
  'Olympic History – Unforgettable moments, medal counts, host cities.',
  'Board Games & Puzzles – Trivial Pursuit, Monopoly, chess trivia.',
  'Soccer / Football – Clubs, players, World Cup trivia.',
  'Baseball Trivia – MLB teams, history, stats.',
  'Tennis – Grand Slam winners, famous matches.',
  'Extreme Sports – X Games, skateboarding, snowboarding.',
  'Esports & Video Games – Games, streamers, tournaments.',
  'NHL & Ice Hockey – Stanley Cup winners, legendary players, rules.',
  'Golf Trivia – The Masters, famous golfers, iconic shots.',
  'Boxing & MMA – Champions, famous bouts, fighting organizations.',
  'Auto Racing – Formula 1, NASCAR, legendary races and drivers.',
  'Track & Field – World records, Olympic heroes, iconic races.',
  'Gymnastics – Olympic champions, scoring, memorable routines.',
  'Cricket – Test matches, World Cups, legendary players.',
  'Rugby – Union, League, World Cups, legendary teams.',
  'Wrestling Entertainment – WWE superstars, iconic matches, storylines.',
  'Winter Sports – Skiing, snowboarding, biathlon, and icy competitions.',

  // FUN & RANDOM
  'Weird But True – Guinness records, strange inventions, odd laws.',
  'Famous Quotes – Identify who said it: from politicians to celebrities.',
  'Famous Firsts – First in history across various fields.',
  'Mythology & Legends – Greek, Norse, Egyptian myths, urban legends.',
  'Pop Culture Moments – Viral trends, memes, internet history.',
  'Fashion & Designers – Iconic styles, brands, runway history.',
  'Toys & Childhood Nostalgia – From Barbie to Pokémon cards.',
  'Languages & Words – Etymology, rare words, language trivia.',
  'Animals in Pop Culture – Famous fictional pets, mascots, and creatures.',
  'Holidays & Traditions – Christmas, Diwali, Halloween customs worldwide.',

  // TECHNOLOGY & DIGITAL LIFE
  'Computers & Internet History – Milestones from ENIAC to the modern web.',
  'Tech Companies & Founders – Apple, Google, Microsoft, and the minds behind them.',
  'Apps & Social Media – Instagram, TikTok, Twitter trivia.',
  'Gadgets Through Time – From Walkmans to smartphones.',
  'Cybersecurity & Hacking – Famous hacks, encryption, and online safety.',
  'Digital Innovations – AI, VR, blockchain, and emerging tech.',
  'Gaming Hardware – Consoles, graphics cards, and retro systems.',
  'Smartphones & Devices – Mobile tech, apps, and market trends.',
  'Tech Buzzwords – Cloud, big data, IoT and what they mean.',
  'Digital Pop Culture – Memes, viral videos, and internet icons.',

  // BUSINESS & ECONOMICS
  'Famous Entrepreneurs – Visionaries who built empires.',
  'Stock Market Basics – Indices, ticker symbols, and Wall Street trivia.',
  'Brands & Logos – Recognize the brand by its logo.',
  'Corporate Scandals – Shocking frauds and business failures.',
  'Advertising & Marketing – Famous slogans, campaigns, and jingles.',
  'Business History – Industrial revolutions, historical companies.',
  'Consumer Products – Everyday items and their origins.',
  'Startups & Unicorns – Companies that boomed fast.',
  'Global Trade – Imports, exports, and trade partners.',
  'Billionaires Club – The world’s wealthiest people and facts about them.',

  // LIFESTYLE & WELLNESS
  'Fitness & Exercise – Workouts, sports science, and trends.',
  'Meditation & Mindfulness – Practices, benefits, and origins.',
  'Healthy Eating – Superfoods, nutrition facts, diet trends.',
  'Fashion Trends – Styles through the decades.',
  'Home Décor & DIY – Interior design, crafting, and home projects.',
  'Pets & Animal Care – Breeds, fun facts, and famous pets.',
  'Gardening & Plants – Flowers, veggies, and gardening trivia.',
  'Travel Hacks – Tips, tricks, and travel trivia.',
  'Personal Finance – Saving, budgeting, and financial literacy.',
  'Self-Care & Happiness – Tips for well-being and feel-good trivia.',
]
